# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               TechTalks
tagline:             'TechTalks'
description:         'TechTalks'
url:                 https://teymur647.github.io/techtalks/
baseurl:             '/techtalks'
paginate:            5

# About/contact
author:
  name:              TechTalks
  url:               https://teymur647.github.io/techtalks/
  email:             teymur.veliyev001@gmail.com

# Custom vars
version:             1.0.0
