# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:year/:month/:day/:title/

# Setup
title:               TechTalks
tagline:             'TechTalks'
description:         'TechTalks'
url:                 https://teymur-valiyev.github.io
baseurl:             '/techtalks'
paginate:            5

# About/contact
author:
  name:              TechTalks
  url:               https://teymur-valiyev.github.io/techtalks/
  email:             teymur.veliyev001@gmail.com
  twitter:           /teymur647
  github:            /teymur-valiyev
  linkedin:            /teymur-valiyev

# Custom vars
version:             1.0.0
